### PR TITLE
 fix: entity motion inconsistencies

### LINKED ISSUE #52: Owner Meta motion is 0 if player doesn't change Y
The values of `motionX` and `motionZ` are 0 if the player doesn't move in the Y axis.

`motionY` should also be `0`, but is `-0.07840000152587890680511151231257827021181583404541015625` instead.

### PR DESCRIPTION
**Pull request by hugeblank**
Fixes SwitchCraftCC/Plethora-Fabric#52. 

Adds a pair of mixins that calculate velocity from the entity's current position and the position in the tick prior.

Test program: 
```lua
local mods = peripheral.wrap("back")
mods.canvas().clear()
local text = mods.canvas().addText({0,0}, "")
while true do
    local meta = mods.getMetaOwner()
    text.setText(meta.motionX.." "..meta.motionY.." "..meta.motionZ)
end
```
Use on NI with introspection module, overlay glasses, and entity sensor. 
Move around, see velocity change.

### CODE REVIEW

**Comment by hugeblank** [comment]
When changing dimensions, for a single tick, the entity velocity spikes. Should this be intended behavior? 
Some alternatives:
1. Providing the dimension the entity is in in the metadata so the player can account for this programmatically.
2. Storing positions per dimension. This has the side effect that when entering the nether, heading to another portal and exiting the nether through it, the overworld velocity will spike. 
3. Assuming the entity's velocity is always 0 when entering any dimension. I think this might be the best bet, but I like the idea of exposing the dimension the entity is in too...

File: src/main/java/io/sc3/plethora/mixin/EntityMixin.java [hunk 1]
```diff
@@ -0,0 +1,26 @@
...
+import net.minecraft.entity.Entity;
+import net.minecraft.util.math.Vec3d;
+import org.spongepowered.asm.mixin.Mixin;
+import org.spongepowered.asm.mixin.Unique;
+
+@Mixin(Entity.class)
+public class EntityMixin implements VelocityDeterminable {
+    @Unique
+    public Vec3d prevPos = Vec3d.ZERO;
+    public Vec3d motion = Vec3d.ZERO;
```
Comment (Lemmmy) [inline src/main/java/io/sc3/plethora/mixin/EntityMixin.java]: Don't forget @Unique here too
```suggestion
    @Unique
    private Vec3d motion = Vec3d.ZERO;
```

File: src/main/java/io/sc3/plethora/mixin/EntityMixin.java [hunk 2]
```diff
@@ -0,0 +1,26 @@
...
+import io.sc3.plethora.util.VelocityDeterminable;
+import net.minecraft.entity.Entity;
+import net.minecraft.util.math.Vec3d;
+import org.spongepowered.asm.mixin.Mixin;
+import org.spongepowered.asm.mixin.Unique;
+
+@Mixin(Entity.class)
+public class EntityMixin implements VelocityDeterminable {
+    @Unique
+    public Vec3d prevPos = Vec3d.ZERO;
```
Comment (Lemmmy) [inline src/main/java/io/sc3/plethora/mixin/EntityMixin.java]:
```suggestion
    private Vec3d prevPos = Vec3d.ZERO;
```

File: src/main/java/io/sc3/plethora/mixin/EntityMixin.java [hunk 3]
```diff
@@ -0,0 +1,26 @@
...
+    public Vec3d motion = Vec3d.ZERO;
+
+    @Override
+    public void storePrevPos() {
+        Vec3d pos = ((Entity)((Object)this)).getPos();
+        motion = pos.subtract(prevPos);
+        prevPos = pos;
+    }
```
Comment (Lemmmy) [inline src/main/java/io/sc3/plethora/mixin/EntityMixin.java]: I don't think the velocity spiking is necessarily bad behavior, but you could store and compare the world here, setting the velocity back to 0 if the dimension is different to the previous tick. Something like this might work:

```suggestion
    @Unique
    private RegistryKey<World> prevWorld;

    @Override
    public void storePrevPos() {
        var entity = (Entity) (Object) this;
        var pos = entity.getPos();
        var world = entity.getWorld().getRegistryKey();
        
        // Avoid velocity spikes when changing dimensions
        if (prevWorld != world) {
            prevWorld = world;
            motion = Vec3d.ZERO;
        } else {
            motion = pos.subtract(prevPos);        
        }
        
        prevPos = pos;
    }
```

Double check this still works with tickPassenger. I believe it will; the prevPos gets observed twice but the world has already changed by the time tickPassenger is called.

**Review by Lemmmy — CHANGES_REQUESTED** [review]

File: src/main/java/io/sc3/plethora/mixin/EntityMixin.java (hunk 3 above)
Comment (hugeblank) [reply src/main/java/io/sc3/plethora/mixin/EntityMixin.java]: Actually, entities that have a passenger suppress the dimension change for both itself and the passenger. The one exception to this that I can think of is parrots, but they:
a) aren't a passenger in the same way that mountable entities are
b) don't get detected by the sensor anyways.

e20bcd3 adds the world-change velocity reset though, it has been tested and works perfectly.

**Review by Lemmmy — APPROVED** [review]

**Comment by Lemmmy** [comment]
LGTM, Huge thanks for this!
